---
title: "Perdiz arrow point shape as a function of site, raw material, and/or mortuary context?"
author: "Robert Z. Selden, Jr."
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Elliptical Fourier Analysis

## Chronology for incised Caddo types

```{r typetemporal, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# load ggplot2
library(ggplot2)
# gantt chart of relative dates for perdiz arrow points
temp<-data.frame(Site = c('Tuck Carpenter', 'Johns', 'Pine Tree Mound', 'Washington Square Mound', 'Spradley', 'Jack Walton', 'Redwine', 'Old Timers', 'Sybs Site'),
                 Date_Range_CE = c(1430,1430,1300,1238,1650,1200,1300,1400,1400), # in years CE
                 end = c(1500,1600,1650,1445,1725,1400,1454,1680,1575) # in years CE
)
# reorder types by beginning of relative date range
temp$Site <- factor(temp$Site, levels = temp$Site[order(temp$Date_Range_CE)])
# arrange figure
type.time <- ggplot(temp, aes(x = Date_Range_CE, xend = end, y = factor(Site, 
       levels = rev(levels(factor(Site)))), yend = Site, color = Site)) +
  geom_segment(size = 1.5) +
  scale_colour_discrete() +
  theme(legend.position = "none") +
  labs(y = "Site", x = "Date Range CE")
# render figure
type.time
```

## Load packages + data

```{r load.packages, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# load packages
library(here)
library(Momocs)

# read images
jpg.list <- list.files(here("/img.perdiz"), full.names = TRUE)

# read attribute data
att.data <- read.csv("perdiz.csv", header = TRUE, as.is = TRUE)

# attribute to factor
att.data$context <- as.factor(att.data$context)
att.data$trinomial <- as.factor(att.data$trinomial)
att.data$raw.mat <- as.factor(att.data$raw.mat)
```

## Generate outlines

```{r outlines + attributes, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# generate outlines
outlines <- jpg.list %>%
  import_jpg()

# add attributes
data.out <- Out(outlines, 
         fac = att.data)

# scale, align, rotate, and center specimens
norm.outlines <- data.out %>% 
  coo_scale() %>%
  coo_align() %>% 
  coo_center()
```

## Pile and mosaics

```{r stack.panel, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# outline pile
pile(norm.outlines)

panel(norm.outlines, names = TRUE)
# mosaic of individual specimens from the different sites
mosaic(norm.outlines, ~trinomial)
# mosaic of individual specimens rendered from different materials
mosaic(norm.outlines, ~raw.mat)
# mosaic of individual specimens from contexts (mortuary/not)
mosaic(norm.outlines, ~context)
```

## Calibrate harmonic + EFA

```{r cal.harm, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# calibrate how many harmonics needed
calibrate_harmonicpower_efourier(norm.outlines, 
                                 nb.h = 30)

# 11 harmonics needed to capture 99 percent of variation
calibrate_reconstructions_efourier(norm.outlines, 
                                   range = 1:11)

# generate efa outlines with 11 harmonics
efa.outlines <- efourier(norm.outlines, 
                         nb.h = 11, 
                         norm = TRUE)

# use efa.outlines for pca
pca.outlines <- PCA(efa.outlines)
```

## PCA

```{r pca.plot, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# pca 
scree_plot(pca.outlines)

# plot pca by site
plot_PCA(pca.outlines, 
         morphospace_position = "range",
         ~trinomial, zoom = 1.2)

# plot pca by raw material
plot_PCA(pca.outlines, 
         morphospace_position = "range",
         ~raw.mat, zoom = 1.2)

# plot pca by context
plot_PCA(pca.outlines, 
         morphospace_position = "range",
         ~context, zoom = 1.2)

# contribution of each pc
# by site
boxplot(pca.outlines, ~trinomial, nax = 1:5)
# by raw material
boxplot(pca.outlines, ~raw.mat, nax = 1:5)
# by raw material
boxplot(pca.outlines, ~context, nax = 1:5)

# mean shape + 2sd for the first 10 pcs
PCcontrib(pca.outlines, nax = 1:5)
```

## MANOVA + MANOVA_PW

```{r manova, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# manova

# shape difference between sites?
MANOVA(pca.outlines, 'trinomial')
# which differ?
MANOVA_PW(pca.outlines, 'trinomial')

# shape difference between raw.mat?
MANOVA(pca.outlines, 'raw.mat')
# which differ?
MANOVA_PW(pca.outlines, 'raw.mat')

# shape difference by context?
MANOVA(pca.outlines, 'context')
```

## Mean shapes

```{r ms1, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# mean shapes

# site
ms.2 <- MSHAPES(efa.outlines, ~trinomial)
plot_MSHAPES(ms.2, size = 0.75)

# raw material
ms.3 <- MSHAPES(efa.outlines, ~raw.mat)
plot_MSHAPES(ms.3, size = 0.75)

# context
ms.4 <- MSHAPES(efa.outlines, ~context)
plot_MSHAPES(ms.4, size = 0.75)
```
