---
title: "X^2"
author: "Robert Z. Selden, Jr."
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## X^2 and descriptive statistics

### Load packages + data
```{r x2.load, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# qualitative data for Perdiz points
library(here)
library(CGPfunctions)
library(lsr)

# read attribute data
data <- as.data.frame(read.csv("perdiz.csv", header = TRUE, as.is = TRUE))

# variables as factors
raw <- as.factor(data$raw.mat) # raw material
con <- as.factor(data$context) # burial context
temp <- as.factor(data$temporal) # temporal period
site <- as.factor(data$trinomial) # site
```

### Comparison of raw material by mortuary context

```{r x2.raw.mort, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
#####
## raw material by burial context
# tables
r.tab <- table(raw, con) # table of raw material by burial context
ftable(r.tab) # flat contingency table
summary(r.tab) # zeros in table
chisq.test(r.tab, correct = FALSE, simulate.p.value = TRUE) # simulate p-value
chisq.test(r.tab, correct = FALSE, simulate.p.value = TRUE)$stdres # residuals
sig <- .05 # significance level
# adjust for multiple testing with Bonferroni
sig.adj <- sig/(nrow(r.tab)*ncol(r.tab))
# z value
qnorm(sig.adj/2) # above Z in residuals = significant

# effect size
cramersV(r.tab)

# number of observations
margin.table(r.tab,1) # raw material
margin.table(r.tab,2) # mortuary/no

# percentages
prop.table(r.tab)
prop.table(r.tab,1) # perc by raw.mat (read l/r)
prop.table(r.tab,2) # perc by mortuary/no (read top to bottom)

# plot cross tabs
PlotXTabs(data, context, raw.mat) # side by side
PlotXTabs(data, context, raw.mat, "stack") # stacked
PlotXTabs(data, context, raw.mat, plottype = "percent") # as percentages
```

### Comparison of raw material by temporal period

```{r x2.raw.temp, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
#####
## raw material by temporal period
# tables
r.tab2 <- table(raw, temp) # table of raw material by temporal period
ftable(r.tab2) # flat contingency table
summary(r.tab2) # zeros in table
chisq.test(r.tab2, simulate.p.value = TRUE) # simulate p-value
chisq.test(r.tab2, correct = FALSE, simulate.p.value = TRUE)$stdres # residuals
sig <- .05 # significance level
# adjust for multiple testing with Bonferroni
sig.adj <- sig/(nrow(r.tab2)*ncol(r.tab2))
# z value
qnorm(sig.adj/2) # above Z in residuals = significant

# effect size
cramersV(r.tab2)

# number of observations
margin.table(r.tab2,1) # raw material
margin.table(r.tab2,2) # temporal period

# percentages
prop.table(r.tab2)
prop.table(r.tab2,1) # perc by raw.mat (read l/r)
prop.table(r.tab2,2) # perc by temporal period (read top to bottom)

# plot cross tabs
PlotXTabs(data, temporal, raw.mat) # side by side
PlotXTabs(data, temporal, raw.mat, "stack") # stacked
PlotXTabs(data, temporal, raw.mat, plottype = "percent") # as percentages

```

### Comparison of raw material by site

```{r x2.raw.site, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
#####
## raw material by site
# tables
r.tab3 <- table(raw, site) #table of raw material by site
ftable(r.tab3) # flat contingency table
summary(r.tab3) # zeros in table
chisq.test(r.tab3, simulate.p.value = TRUE) # simulate p-value
chisq.test(r.tab3, correct = FALSE, simulate.p.value = TRUE)$stdres # residuals
sig <- .05 # significance level
# adjust for multiple testing with Bonferroni
sig.adj <- sig/(nrow(r.tab3)*ncol(r.tab3))
# z value
qnorm(sig.adj/2) # above Z in residuals = significant

# effect size
cramersV(r.tab3)

# number of observations
margin.table(r.tab3,1) # raw material
margin.table(r.tab3,2) # site

# percentages
prop.table(r.tab3)
prop.table(r.tab3,1) # perc by raw.mat (read l/r)
prop.table(r.tab3,2) # perc by site (read top to bottom)

# plot cross tabs
PlotXTabs(data, trinomial, raw.mat) # side by side
PlotXTabs(data, trinomial, raw.mat, "stack") # stacked
PlotXTabs(data, trinomial, raw.mat, plottype = "percent") # as percentages
```
