# Elliptical Fourier Analysis

## Load packages + data

```{r load.packages, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# load packages
#devtools::install_github("MomX/Momocs")
library(here)
library(Momocs)

# read images
jpg.list <- list.files(here("img.perdiz"), full.names = TRUE)

# read attribute data
att.data <- read.csv("perdiz.csv", header = TRUE, as.is = TRUE)

# attribute to factor
att.data$temporal <- as.factor(att.data$temporal)
att.data$context <- as.factor(att.data$context)
att.data$raw.mat <- as.factor(att.data$raw.mat)
att.data$contemp <- as.factor(att.data$contemp)
att.data$contempraw <- as.factor(att.data$contempraw)
```

## Generate outlines

```{r outlines + attributes, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# generate outlines
outlines <- jpg.list %>%
  import_jpg()

# add attributes
data.out <- Out(outlines, 
         fac = att.data)

# scale, align, rotate, and center specimens
norm.outlines <- data.out %>% 
  coo_scale() %>%
  coo_align() %>% 
  coo_center()
```

## Calibrate harmonic + EFA

```{r cal.harm, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# calibrate how many harmonics needed
calibrate_harmonicpower_efourier(norm.outlines, 
                                 nb.h = 30)

# 11 harmonics needed to capture 99 percent of variation
calibrate_reconstructions_efourier(norm.outlines, 
                                   range = 1:11)

# generate efa outlines with 11 harmonics
efa.outlines <- efourier(norm.outlines, 
                         nb.h = 11, 
                         norm = TRUE)

# use efa.outlines for pca
pca.outlines <- PCA(efa.outlines)
```

## PCA

```{r pca.plot, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# pca 
scree_plot(pca.outlines)

# plot pca by raw material
plot(pca.outlines,
     pos.shp = "range_axes",
     ~raw.mat,
     chull = TRUE,
     morphospace = TRUE,
     labelsgroups = TRUE,
     cex.labelsgroups = 0.5,
     rect.labelsgroups = TRUE,
     rug = TRUE,
     grid = TRUE,
     zoom = 0.95)

# plot pca by context
plot(pca.outlines,
     pos.shp = "range_axes",
     ~context,
     chull = TRUE,
     morphospace = TRUE,
     labelsgroups = TRUE,
     cex.labelsgroups = 0.5,
     rect.labelsgroups = TRUE,
     rug = TRUE,
     grid = TRUE,
     zoom = 0.95)

# plot pca by temporal
plot(pca.outlines,
     pos.shp = "range_axes",
     ~temporal,
     chull = TRUE,
     morphospace = TRUE,
     labelsgroups = TRUE,
     cex.labelsgroups = 0.5,
     rect.labelsgroups = TRUE,
     rug = TRUE,
     grid = TRUE,
     zoom = 0.95)

# plot pca by contemp
plot(pca.outlines,
     pos.shp = "range_axes",
     ~contemp,
     chull = TRUE,
     morphospace = TRUE,
     labelsgroups = TRUE,
     cex.labelsgroups = 0.5,
     rect.labelsgroups = TRUE,
     rug = TRUE,
     grid = TRUE,
     zoom = 0.95)

# plot pca by contempraw
plot(pca.outlines,
     pos.shp = "range_axes",
     ~contempraw,
     chull = TRUE,
     morphospace = TRUE,
     labelsgroups = TRUE,
     cex.labelsgroups = 0.5,
     rect.labelsgroups = TRUE,
     rug = TRUE,
     grid = TRUE,
     zoom = 0.95)

# mean shape + 2sd for the first 10 pcs
PCcontrib(pca.outlines, nax = 1:5)
```

## MANOVA + MANOVA_PW

```{r manova, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# manova

# shape difference between raw.mat?
MANOVA(pca.outlines, 'raw.mat')
# which differ?
MANOVA_PW(pca.outlines, 'raw.mat')

# shape difference by context?
MANOVA(pca.outlines, 'context')

# shape difference by temporal?
MANOVA(pca.outlines, 'temporal')
# which differ?
MANOVA_PW(pca.outlines, 'temporal')

# shape difference by contemp?
MANOVA(pca.outlines, 'contemp')
# which differ?
MANOVA_PW(pca.outlines, 'contemp')

# shape difference by contempraw?
MANOVA(pca.outlines, 'contempraw')
# which differ?
MANOVA_PW(pca.outlines, 'contempraw')
```

## Mean shapes

```{r ms1, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# mean shapes

# raw material
ms.3 <- MSHAPES(efa.outlines, ~raw.mat)
plot_MSHAPES(ms.3, size = 0.75)

# context
ms.4 <- MSHAPES(efa.outlines, ~context)
plot_MSHAPES(ms.4, size = 0.75)

# temporal
ms.5 <- MSHAPES(efa.outlines, ~temporal)
plot_MSHAPES(ms.5, size = 0.75)

# contemp
ms.5 <- MSHAPES(efa.outlines, ~contemp)
plot_MSHAPES(ms.5, size = 0.75)

# contempraw
ms.6 <- MSHAPES(efa.outlines, ~contempraw)
plot_MSHAPES(ms.6, size = 0.75)
```
